modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="s3_progression_mod"
version="${mod_version}"
displayName="Progression Mod"
authors="CivTFG"
description='''
Laboratory block that fires progression events for KubeJS.
'''

[[dependencies.s3_progression_mod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="kubejs"
    mandatory=true
    versionRange="[2001.6.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="ftblibrary"
    mandatory=true
    versionRange="[2001.2.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="gamestages"
    mandatory=true
    versionRange="[15.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="ftbteams"
    mandatory=true
    versionRange="[2001.3.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.s3_progression_mod]]
    modId="ftbchunks"
    mandatory=true
    versionRange="[2001.3.8,)"
    ordering="NONE"
    side="BOTH"